#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
sudo apt-get -y update
sudo apt-get -y install haproxy
TMPFILE=`tempfile`
cat << EOF > $TMPFILE
frontend front_server
	bind *:80
	mode http
	default_backend backend_server
backend backend_server
	balance roundrobin
	server 4322-web-01 34.207.236.163:80 check
	server 4322-web-02 107.20.69.130:80 check
EOF

sudo cp $TMPFILE /etc/haproxy/haproxy.cfg
rm $TMPFILE
sudo echo "ENABLED=1" >> /etc/default/haproxy
sudo service haproxy restart
