#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
sudo apt-get -y update
sudo apt-get -y install haproxy
TMPFILE=`tempfile`
cat << EOF > $TMPFILE
frontend front_server
	bind *:80
	mode http
	default_backend backend_server
backend backend_server
	balance roundrobin
	server 7074-web-01 34.237.51.17:80 check
	server 7074-web-02 44.192.95.90:80 check
EOF

sudo cp $TMPFILE /etc/haproxy/haproxy.cfg
rm $TMPFILE
sudo echo "ENABLED=1" >> /etc/default/haproxy
sudo service haproxy restart
