#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

sudo apt-get -y update
sudo apt-get -y install haproxy

sudo cat >> /etc/haproxy/haproxy.cfg << EOF
frontend front_server
	bind *:80
	mode http
	default_backend backend_server
backend backend_server
	balance roundrobin
	server 7074-web-01 3.237.15.144:80 check
	server 7074-web-01 3.233.226.6:80 check
EOF

sudo echo "ENABLED=1" >> /etc/default/haproxy
sudo service haproxy restart
