#!/usr/bin/env bash
# Fixes the nginx listening port and reloads the nginx master process
sudo sed -i 's/listen 8080/listen 80/g' /etc/nginx/sites-enabled/default
sudo sed -i 's/listen \[::\]:8080/listen \[::\]:80/g' /etc/nginx/sites-enabled/default
pgrep nginx -o > /run/nginx.pid
sudo nginx -s reload
echo '' > /run/nginx.pid